global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'youremail@gmail.com'
  smtp_auth_username: 'youremail@gmail.com'
  smtp_auth_password: 'YOUR GMAIL APP PASSWORD'
  smtp_require_tls: true

route:
  receiver: 'gmail-notifications'
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 30s

receivers:
  - name: 'gmail-notifications'
    email_configs:
      - to: 'youremail@gmail.com'
        send_resolved: true

    webhook_configs:
      - url: 'http://localhost:4000/alert'
        send_resolved: true