name: Debug Runner

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Keep runner alive
        run: |
          echo "Runner is alive"
          tail -f /dev/null
