name: My first workflow
on: [push, workflow_dispatch]
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check NodeJS Version
        run: node -v
      - name: Install NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Check NodeJS Version
        run: node -v

  # my-first-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: List all files
  #       run: ls -a
  #     - name: Print Working Directory
  #       run: pwd
  #     - name: Checkout Repo
  #       uses: actions/checkout@v6
  #     - name: Print Workflow file contents
  #       run: cat ./.github/workflows/main.yml
